# Generated by Django 5.2.4 on 2025-07-28 06:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_mode',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('WORK_FROM_OFFICE', 'Work from Office'), ('WORK_FROM_HOME', 'Work from Home'), ('HYBRID', 'Hybrid')], max_length=20), blank=True, default=list, size=None),
        ),
    ]
