# .pre-commit-config.yaml

repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        exclude: (^.*/migrations/.*)$

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        exclude: (^.*/migrations/.*)$
        args: [--max-line-length=120]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
        exclude: (^.*/migrations/.*)$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        args: [--format=txt, --quiet]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: debug-statements
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: requirements-txt-fixer
      - id: check-added-large-files
        args: [--maxkb=550]

  - repo: local
    hooks:
      - id: django-check
        name: django-check
        entry: bash -c 'python manage.py check'
        language: system
        types: [python]
        pass_filenames: false

  - repo: local
    hooks:
      - id: prospector
        name: prospector
        entry: prospector
        language: system
        types: [python]
        pass_filenames: false
        args:
          - --profile-path=.
          - --profile=.prospector
